server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway: 
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          #uri: http://localhost:9098/
          uri: lb://customer-service
          predicates:
            #- Path=/customers/**
            - Path=/example/**
        - id: test-service
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/todos/**
